version: '3.8'

services:
  # MongoDB Database
  mongo:
    image: mongo:7
    container_name: spill-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=spill-app
    networks:
      - spill-network

  # Backend API
  api:
    build: ./backend
    container_name: spill-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/spill-app
      - JWT_SECRET=${JWT_SECRET:-change-me-in-production}
      - SENTRY_DSN=${SENTRY_DSN}
    depends_on:
      - mongo
    networks:
      - spill-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongo-data:
    driver: local

networks:
  spill-network:
    driver: bridge
